#DIRECTORY WAAR DE FASTQ BESTANDEN ZITTEN
DIRECTORY_FQ: /exports/BNGP/reads/

#DIRECTORY WAAR HET REFGENOOM ZIT
REFGENOME: /exports/BNGP/refgenome/listeria-edge.fa
REFGENOME_BASE_NAME: listeria-edge.fa

#FILTER EN TRIMMING PARAMETERS
TRIM_BASES: 5
MIN_PHRED: 12.0
MIN_LENGTH: 500

DIST_TO_NEWICK: /exports/BNGP/scripts/dist_to_newick.py 